---
- name: Set Hostname
  hosts: web2
  become: true
  tasks:
    - name: Set the hostname
      ansible.builtin.hostname:
        name: "{{ new_hostname }}"

    - name: Update /etc/hosts with the new hostname
      lineinfile:
        path: /etc/hosts
        regexp: "^127\\.0\\.1\\.1\\s"
        line: "127.0.1.1 {{ new_hostname }}"
        state: present
      become: true
